### ISSUE TITLE
Select_algorithm in MOpt havoc stage

### ISSUE THREAD

**Issue by borg-a** [AFLplusplus/AFLplusplus#1394]
Hello, 

I was looking at the code for the havoc stage in the **mopt_common_fuzzing** function. From my understanding, select_algorithm randomly chooses a mutator index according to the given probabilities, and that is then applied in the subsequent switch.

There are 19 mutators (according to the switch cases): 
0 : STAGE_FLIP1
1 : STAGE_FLIP2
2 : STAGE_FLIP4
3 : STAGE_FLIP8
4 : STAGE_FLIP16
5 : STAGE_FLIP32
6 : STAGE_ARITH8
7 : STAGE_ARITH16
8 : STAGE_ARITH32
9 : STAGE_INTEREST8
10 : STAGE_INTEREST16
11 : STAGE_INTEREST32
12 : STAGE_RANDOMBYTE
13 : STAGE_DELETEBYTE
14 : STAGE_Clone75
15 : STAGE_OverWrite75
16 : STAGE_OverWriteExtra
17 : STAGE_InsertExtra
18 : STAGE_Splice

But the r_max value is initialized every time to: 15 + eventually 2 + eventually 1 (max 18)

```
      u32 r_max;

      r_max = 15 + ((afl->extras_cnt + afl->a_extras_cnt) ? 2 : 0);

      if (unlikely(afl->expand_havoc && afl->ready_for_splicing_count > 1)) {

        /* add expensive havoc cases here, they are activated after a full
           cycle without finds happened */

        ++r_max;

      }
```
**And select_algorithm will use the probability of (r_max - 1) indexed mutator as the maximum range for choosing one, this means it can get at most to [17 : STAGE_InsertExtra] when r_max is the maximum possible value. 
And STAGE_Splice is never enabled.**

Am I missing something? Is this, for any reason, intended?
Also, it seems, from the names, that everything is kind of shifted. extras +2 just adds one of the two mutators with Extra and the other +1 adds the other ( InsertExtra)...

Thanks

**Comment by akasong** [comment]
I was also looking at this code. And I found it is different from vanilla MOpt (missmatched array number in select_algorithm).

afl++'s r_max : 15 or 17  (not 16, 18 unless set env value AFL_EXPAND_HAVOC_NOW)
so index of the array number in select_algorithm() is 14(STAGE_Clone75) or 16(STAGE_OverWriteExtra).

In select_algorithm() of vanilla MOpt, this array number is 15(STAGE_OverWrite75) or 17(STAGE_InsertExtra).

Is this intended?

**Comment by vanhauser-thc** [comment]
@borg-a thank you for pointing this out! yes that was a fuck up of me when I added the extra splicing part. 

While fixing the code and further reviewing I found another fuckup that we inherited from vanilla AFL - there was user token insert, user token overwrite, auto extra overwrite - but no auto extra insert was ever implemented. so I fixed that too (FYI @andreafioraldi) 

0b228fb tries to fix both, if you would be so kind to review if this looks good now.

@akasong can you also have a look if this fixes too what you meant or if I just didnt understand you correctly (in this case please rephrase the potential issue you identified).

**Comment by borg-a** [comment]
Hi @vanhauser-thc , thanks for your reply. 

I had a look at the fixed code and there's still one thing that seems wrong to me, the initialization of r_max.

From my understanding, the method *static int select_algorithm(afl_state_t *afl, u32 max_algorithm)** returns a value, randomly sampled according to the given probabilities, between 0 and (max_algorithm - 1).

Now, when you call it with r_max == 15 (default situation, without extras or splicing), the maximum possible returned value is 14, but the default operators are 16, with indices 0 .. 15 (switch cases are from 0 to 15).
Therefore, I would change r_max initialization:

r_max = **15** + ((afl->extras_cnt + afl->a_extras_cnt) ? 2 : 0); 
to
r_max = **16** + ((afl->extras_cnt + afl->a_extras_cnt) ? 2 : 0); 

or change the select_algorithm method to include the 'max_algorithm' value as a possible return value.

Do you agree? Am I missing something?

**Comment by vanhauser-thc** [comment]
> Hi @vanhauser-thc , thanks for your reply.
> 
> I had a look at the fixed code and there's still one thing that seems wrong to me, the initialization of r_max.
> 
> From my understanding, the method _static int select_algorithm(afl_state_t _afl, u32 max_algorithm)__ returns a value, randomly sampled according to the given probabilities, between 0 and (max_algorithm - 1).
> 
> Now, when you call it with r_max == 15 (default situation, without extras or splicing), the maximum possible returned value is 14, but the default operators are 16, with indices 0 .. 15 (switch cases are from 0 to 15). Therefore, I would change r_max initialization:
> 
> r_max = **15** + ((afl->extras_cnt + afl->a_extras_cnt) ? 2 : 0); to r_max = **16** + ((afl->extras_cnt + afl->a_extras_cnt) ? 2 : 0);
> 
> or change the select_algorithm method to include the 'max_algorithm' value as a possible return value.
> 
> Do you agree? Am I missing something?

you are absolutely right, thankfully I don't think I write perfect code, and ask people to review instead :)
293e255 should fix this.

**Comment by borg-a** [comment]
Still have a couple of doubts:
- Shouldn't it be r -= 16? The case where you get to the default is when r > 15, and then you're checking r == 0 and r == 1 for the extras. I believe these should be r == 16 -> 0 and r == 17 -> 1, and so that should be r -= 16 instead of r -= 15.

- Is the '}' at line 5031 supposed to be there? Seems to immediately close the default case.

**Comment by vanhauser-thc** [comment]
man I can really not code today. coming back from an exhausting vacation and doing different important things at the same time is not good either ... hopefully it is fine now ... 68e8467

**Comment by borg-a** [comment]
No more doubts from my side now :)

**Comment by akasong** [comment]
Thanks @vanhauser-thc seems alright.

**Comment by akasong** [comment]
Thanks @vanhauser-thc everything seems alright.

**Comment by akasong** [comment]
everything seems alright. Thanks.

**Comment by vanhauser-thc** [comment]
thank you both!
