### ISSUE TITLE
[bug] afl-fuzz -R (Radamsa) no longer works

### ISSUE THREAD

**Issue by jonasmollerlarsen** [AFLplusplus/AFLplusplus#419]
Since the port to Haiku in
https://github.com/AFLplusplus/AFLplusplus/commit/67d87dd2a9dbc393b56162e77ff3178f4e3f59fa

```
$ afl-fuzz -i seed/ -o findings/ -R -- ./fuzz_target
```
quits with exit code 1, at the point of starting the radamsa stage, under Ubuntu 16.04.6 LTS (WSL) llvm-9.0.0.

strace output:
```
$ strace afl-fuzz -i seed/ -o findings/ -R -- ./fuzz_target
...
...
read(8, "\177\23\0\0", 4)               = 4
gettimeofday({1592671320, 952673}, {tz_minuteswest=0, tz_dsttime=0}) = 0
kill(32206, SIGKILL)                    = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=32206, si_uid=1000, si_status=SIGKILL, si_utime=0, si_stime=0} ---
exit_group(1)                           = ?
+++ exited with 1 +++
```

libradamsa.c isn't exactly easy to follow, but it appears that the order of constants matters in

```
2416,2418c2416,2421
<             FD_CLOEXEC, F_DUPFD, F_DUPFD_CLOEXEC, F_GETFD, F_SETFD, F_GETFL, F_SETFL, F_GETOWN,
<             F_SETOWN, F_GETLK, F_SETLK, F_SETLKW, F_RDLCK, F_UNLCK, F_WRLCK, CLOCK_MONOTONIC,
<             CLOCK_PROCESS_CPUTIME_ID, CLOCK_REALTIME, CLOCK_THREAD_CPUTIME_ID
---
>             FD_CLOEXEC, F_DUPFD, F_DUPFD_CLOEXEC, F_GETFD, F_SETFD, F_GETFL, F_SETFL,
>             F_GETLK, F_SETLK, F_SETLKW, F_RDLCK, F_UNLCK, F_WRLCK, CLOCK_MONOTONIC,
>             CLOCK_PROCESS_CPUTIME_ID, CLOCK_REALTIME, CLOCK_THREAD_CPUTIME_ID,
> #if !defined __HAIKU__
>             F_GETOWN, F_SETOWN
> #endif
```
Undoing just this change is enough to fix the failure.

**Comment by hexcoder-** [comment]
Thanks for a good error analysis! The order of items seems to be relevant here.

**Comment by hexcoder-** [comment]
Now fixed with commit https://github.com/AFLplusplus/AFLplusplus/commit/b3b016a4a3f15ea22eccd06b47dbf9749b6f08ec

**Comment by vanhauser-thc** [comment]
@jonasmollerlarsen please verify that the fix works for you. if so please close the issue :)

**Comment by jonasmollerlarsen** [comment]
Thanks for the fix, -R runs without error now.
On Haiku though, I guess we may need
```
#if defined __HAIKU__
    0, 0,   /* placeholder, to keep indices consistent */
#else
    F_GETOWN, F_SETOWN,
#endif
```

Ignoring Radamsa for a second, the latest master (and dev) branch still doesn't work for me, e.g. it fails to find new paths in a toy 2-byte magic word target. Where 2.65c works fine.

**Comment by vanhauser-thc** [comment]
> Ignoring Radamsa for a second, the latest master (and dev) branch still doesn't work for me, e.g. it fails to find new paths in a toy 2-byte magic word target. Where 2.65c works fine.

this needs way more information.
please provide everything so we can try to reproduce this :)

**Comment by jonasmollerlarsen** [comment]
@vanhauser-thc I'll do some more digging and attempt to provide reproduce info

**Comment by jonasmollerlarsen** [comment]
Here's more info:
The issue I see (no new paths found on a simple target) happens only when using "afl-fuzz -s 0" (fixed random number seed). Without -s the latest master works fine. Different seeds than 0 results in some paths being found, but fuzzing still seems to get stuck (because havoc isn't working?). The issue wasn't there in 2.65 nor https://github.com/AFLplusplus/AFLplusplus/commit/12bdefe00e38cdc3dd8cb028eeac325ab2e94e16.

Can you reproduce?
Thanks!

**Comment by domenukk** [comment]
@vanhauser-thc sounds related to the new random function?

**Comment by vanhauser-thc** [comment]
oh yes -s0 is an issue. every random input will be 0 ... OK I think will change this

**Comment by vanhauser-thc** [comment]
@jonasmollerlarsen please again try with the new dev commit

**Comment by jonasmollerlarsen** [comment]
With the latest dev b0866f59ccbcd90c2c3e0ecbb5ba2d9badc60319 and -s0, rand_next() always returns zero, so afl-fuzz doesn't find paths.
With other seeds -s1 -s2 -s3 the output looks more random.

**Comment by vanhauser-thc** [comment]
I compared the wrong variable ... ;)
eb3cb4bb should fix this.

**Comment by jonasmollerlarsen** [comment]
Both -R and -s 0 work now.

**Comment by domenukk** [comment]
Should we add a unittest for random with seed 0?
