### ISSUE TITLE
afl-clang-fast ignoring -sanitize-coverage-allowlist/sanitize-coverage-blocklist flags

### ISSUE THREAD

**Issue by n30m1nd** [AFLplusplus/AFLplusplus#602]
I'm doing some tests and afl-clang-fast seemed to ignore the `-fsanitize-coverage-allowlist` and `-fsanitize-coverage-blocklist` switches. However, the classic instrumentation mode did comply with the contents of the `AFL_LLVM_INSTRUMENT_FILE`.

### Using AFL_LLVM_INSTRUMENT_FILE
```bash
$ export AFL_LLVM_INSTRUMENT_FILE=./instr.txt
$ afl-clang-fast++  aflfuzz.cc -o aflfuzzer 
[!] WARNING: switching to classic instrumentation because AFL_LLVM_ALLOWLIST/DENYLIST does not work with PCGUARD. Use -fsanitize-coverage-allowlist=allowlist.txt or -fsanitize-coverage-blocklist=denylist.txt if you want to use PCGUARD. Requires llvm 12+. See https://clang.llvm.org/docs/ SanitizerCoverage.html#partially-disabling-instrumentation
afl-cc ++3.00a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-CLASSIC
afl-llvm-pass++3.00a by <lszekeres@google.com> and <adrian.herrera@anu.edu.au>
Info: Found constructor function _GLOBAL__sub_I_aflfuzz.cc with prio 65535, we will not instrument this, putting it into a block list.
[+] Instrumented 12 locations (non-hardened mode, ratio 100%).
```

### Using -fsanitize-coverage-allowlist
```bash
$ unset AFL_LLVM_INSTRUMENT_FILE
$ afl-clang-fast++  -fsanitize-coverage-allowlist=./instr.txt aflfuzz.cc -o aflfuzzer 
afl-cc ++3.00a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
SanitizerCoveragePCGUARD++3.00a
[+] Instrumented 20 locations with no collisions (non-hardened mode).
```

The latter just ignores the switch and instruments all locations. By doing further inspection with `strace` I managed to observe that the switches are passed down the line to `clang++`, but also the `/usr/local/lib/afl/afl-compiler-rt.o` and `/usr/local/lib/afl/SanitizerCoveragePCGUARD.so` get added which I assume are the ones that are not complying with said switches.

For completion, here are the `instr.txt` and `aflfuzz.cc` files:
#### instr.txt
```
src:*aflfuzz.cc
fun:*sum*
```
#### aflfuzz.cc
```cpp
#include <unistd.h>
#include <stdio.h>
#include <iostream>

__AFL_FUZZ_INIT();

int nonused(int a) {
	return a+5;
}

const uint8_t* sum(const uint8_t* a, size_t b) {
	if (a[0] == '1') {
		std::cout << "whoa" << std::endl;
	}
	if (b < 5) return a;
	if (a[1] == 'b' && a[2] == 'x' && a[0] == 'm' && a[5] == '9') {
		abort();
	}
	return a;
}

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
	sum(data, size);
	return 0;
}


int main(int argc, char* argv[]) {
#ifdef __AFL_HAVE_MANUAL_CONTROL
	__AFL_INIT();
#endif
	uint8_t *buf = __AFL_FUZZ_TESTCASE_BUF;

	while (__AFL_LOOP(40000)) {
		size_t len = __AFL_FUZZ_TESTCASE_LEN;
		LLVMFuzzerTestOneInput(buf, len);
	}
}
```

**Comment by vanhauser-thc** [comment]
Thanks for the report.
when you use clang++ with these options and `-fsanitize-coverage=trace-pc-guard` - do they then get instrumented?

it might be that loading our own coverage module prevents access to the files. but if this is the case then I will find a workaround

**Comment by n30m1nd** [comment]
Thanks for the prompt reply :)

Indeed, using either `-fsanitize-coverage=trace-pc-guard` / `-fsanitize=fuzzer` and then running with libFuzzer or honggfuzz works as expected. 
In the case of libfuzzer, I made a test with `src:doesnotexist.cc` and libfuzzer would just bail out due to no instrumentation. If I then added `src:libfuzz.cc`, it would detect the instrumentation and run the fuzzer:

```bash
$ clang++ -fsanitize-coverage-allowlist=./doesnotexist.txt libfuzz.cc -fsanitize=fuzzer -o libfuzzer 
$ ./libfuzzer 
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1371720458
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2	INITED exec/s: 0 rss: 27Mb
ERROR: no interesting inputs were found. Is the code instrumented for coverage? Exiting.
```
Then with the `instr.txt` file with contents:
```
src:*libfuzz.cc
fun:*sum*
```
```
$ clang++ -fsanitize-coverage-allowlist=./instr.txt libfuzz.cc -fsanitize=fuzzer -o libfuzzer 
$ ./libfuzzer | uniq -c
INFO: Running with entropic power schedule (0xFF, 100).
[...]
#2	INITED cov: 3 ft: 4 corp: 1/1b exec/s: 0 rss: 27Mb
[...]
#73764	NEW    cov: 8 ft: 9 corp: 6/22b lim: 724 exec/s: 0 rss: 27Mb L: 5/5 MS: 2 CMP-EraseBytes- DE: "\x00\x00\x00m"-
==2001622== ERROR: libFuzzer: deadly signal
    #0 0x4b0320 in __sanitizer_print_stack_trace (/home/javier/Research/instrafl/libfuzzer+0x4b0320)
[...]
    #16 0x40787d in _start (/home/javier/Research/instrafl/libfuzzer+0x40787d)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 1 CMP- DE: "9\x00\x00\x00"-; base unit: 5d42679a8ca29117b3e9324b3c6cf540468ea930
0x6d,0x62,0x78,0x2e,0x62,0x39,0x0,0x0,0x0,
mbx.b9\x00\x00\x00
artifact_prefix='./'; Test unit written to ./crash-0d372f8b9d46e6b2781d06dc6a8db8afe0d65a06
Base64: bWJ4LmI5AAAA
   7154 whoa
```

#### libfuzz.cc
```cpp
#include <unistd.h>
#include <stdio.h>
#include <iostream>

int nonused(int a) {
        return a+5;
}

const uint8_t* sum(const uint8_t* a, size_t b) {
        if (a[0] == '1') {
                std::cout << "whoa" << std::endl;
        }
        if (b < 5) return a;
        if (a[1] == 'b' && a[2] == 'x' && a[0] == 'm' && a[5] == '9') {
                abort();
        }
        return a;
}

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
        sum(data, size);
        return 0;
}
```

**Comment by vanhauser-thc** [comment]
you can use the clang++ compiled target with afl-fuzz (with -fsanitize-coverage=..) if you add afl-compiler-rt.o when linking.

I will look for a fix for this the next days

**Comment by n30m1nd** [comment]
I tried with the following command line compilation and it didn't seem to instrument anything either, surely this is mostly [pebkac](https://www.urbandictionary.com/define.php?term=pebkac). Had to add all these `-D` options since the documentation for the `__AFL_LOOP(x)` define, [is incomplete](https://github.com/AFLplusplus/AFLplusplus/blame/stable/instrumentation/README.persistent_mode.md#L65).

Here's what I used but it didn't introduce any instrumentation that `afl-fuzz` could be guided with:
```
$ clang++ -fsanitize-coverage-allowlist=./instr.txt aflfuzz.cc -o aflfuzzer \
-D"__AFL_FUZZ_INIT()=int __afl_sharedmem_fuzzing = 1;extern unsigned int *__afl_fuzz_len;extern unsigned char *__afl_fuzz_ptr;unsigned char __afl_fuzz_alt[1048576];unsigned char *__afl_fuzz_alt_ptr = __afl_fuzz_alt;" \
-D"__AFL_FUZZ_TESTCASE_BUF=(__afl_fuzz_ptr ? __afl_fuzz_ptr : __afl_fuzz_alt_ptr)" \
-D"__AFL_FUZZ_TESTCASE_LEN=(__afl_fuzz_ptr ? *__afl_fuzz_len : (*__afl_fuzz_len = read(0, __afl_fuzz_alt_ptr, 1048576)) == 0xffffffff ? 0 : *__afl_fuzz_len)" \
-D"__AFL_LOOP(_A)=({ static volatile char *_B __attribute__((used));  _B = (char*)\"##SIG_AFL_PERSISTENT##\"; __attribute__((visibility(\"default\"))) int _L(unsigned int) __asm__(\"__afl_persistent_loop\"); _L(_A); })" \
-D"__AFL_INIT()=do { static volatile char *_A __attribute__((used));  _A = (char*)\"##SIG_AFL_DEFER_FORKSRV##\"; __attribute__((visibility(\"default\"))) void _I(void) __asm__(\"__afl_manual_init\"); _I(); } while (0)"
clang: warning: argument unused during compilation: '-fsanitize-coverage-allowlist=./instr.txt' [-Wunused-command-line-argument]
```
If I added `-fsanitize=fuzzer-no-link` it would compile cleanly without the warning, but the result would be the same.

Again, thank you for your time!

**Comment by vanhauser-thc** [comment]
@n30m1nd I pushed a fix to dev. 
-fsanitize-coverage-allowlist can sadly not easily work with our own PCGUARD module because it is loaded as an extra. at least I found not an easy way.
But it supports the AFL_LLVM_INSTRUMENT_ALLOW/AFL_LLVM_INSTRUMENT_DENY envs now.
please test.

`clang++ -fsanitize-coverage-allowlist=./instr.txt aflfuzz.cc -o aflfuzzer` <- this is missing `-fsanitize-coverage=trace-pc-guard` and `afl-compiler-rt.o`

**Comment by n30m1nd** [comment]
@vanhauser-thc it looks like it still doesn't honour the `AFL_LLVM_INSTRUMENT_ALLOW`/`AFL_LLVM_INSTRUMENT_DENY` variables.

For completion, I did:
```
$ git pull origin dev
...
$ make clean
...
$ make all && sudo make install
```
Then, on the test program:
```
$ AFL_LLVM_INSTRUMENT_DENY=./instr.txt afl-clang-fast++ aflfuzz.cc -o aflfuzzer
[!] WARNING: Mistyped AFL environment variable: AFL_LLVM_INSTRUMENT_DENY=./instr.txt
afl-cc ++3.00a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
SanitizerCoveragePCGUARD++3.00a
Info: Found constructor function _GLOBAL__sub_I_aflfuzz.cc with prio 65535, we will not instrument this, putting it into a block list.
[+] Instrumented 18 locations with no collisions (non-hardened mode).
```
It's complaining that it can't find the environment variable with `[!] WARNING: Mistyped AFL environment variable: AFL_LLVM_INSTRUMENT_DENY=./instr.txt`. The only place I could see it in the newly pushed code was [here](https://github.com/AFLplusplus/AFLplusplus/blob/4c59c5234aec0469e4dd02561dbd84387bd53155/src/afl-cc.c#L1328). I couldn't see any new `getenv` code for these.

**Comment by vanhauser-thc** [comment]
I abbreviated the env's name. you can find them in the docs. its:
AFL_LLVM_ALLOWLIST or FL_LLVM_DENYLIST (or AFL_LLVM_BLOCKLIST)

**Comment by n30m1nd** [comment]
Can confirm this works. See 11 locations instrumented instead of the above 18. 
```
$ AFL_LLVM_ALLOWLIST=./instr.txt afl-clang-fast++ aflfuzz.cc -o aflfuzzer
afl-cc ++3.00a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
SanitizerCoveragePCGUARD++3.00a
Info: Found constructor function _GLOBAL__sub_I_aflfuzz.cc with prio 65535, we will not instrument this, putting it into a block list.
[+] Instrumented 11 locations with no collisions (non-hardened mode).
```
Just one small caveat of making these mutually exclusive, it doesn't cater for the use case of just instrumenting one big file and not instrumenting certain functions. For example, I have a file called `assembler.cc` on a very big project. The AFL_LLVM_ALLOWLIST file would be:
```
src:*assembler.cc
```
But then, inside that file, there are Random Number Generator functions, all containing `rng` and `Random` string, so I would need now a AFL_LLVM_BLOCKLIST with the following contents:
```
src:*assembler.cc
fun:*rng*
fun:*Random*
```
This works in `clang` but currently not supported by AFL since the environment variables are mutually exclusive.
```
[-] PROGRAM ABORT : You can only specify either AFL_LLVM_ALLOWLIST or AFL_LLVM_DENYLIST but not both!
```

This said, the fix works so I'll close this issue, since what I mentioned above is actually a feature request that belongs on a different ticket.

Million thanks for acting on this so quickly @vanhauser-thc!!
